#!/usr/bin/env python3
"""Fail on NEW comment blocks over one line, in every language the family tracks.

docs/code-quality-tooling.md#comment-size-comment-size
"""
import argparse
import io
import os
import re
import sys
import tokenize

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from quality_allow import check_keys, load_keys  # noqa: E402
import gate_scope  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ALLOW = os.path.join(os.path.dirname(os.path.abspath(__file__)), "comment-size.allow")
LIMIT = int(os.environ.get("COMMENT_SIZE_LIMIT", "1"))

HASH = {".sh", ".bash", ".py", ".ps1", ".psm1", ".psd1", ".yml", ".yaml", ".toml", ".cmake"}
SLASH = {".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx", ".cu", ".hip", ".m", ".mm", ".rs", ".dart",
         ".go", ".js", ".jsx", ".ts", ".tsx", ".java", ".kt", ".cs", ".swift", ".glsl", ".hlsl", ".slang",
         ".vert", ".frag", ".comp"}
HASH_NAMES = ("Dockerfile", "CMakeLists.txt", "Makefile")
PATTERNS = ["*" + e for e in sorted(HASH | SLASH)] + ["*" + n + "*" for n in HASH_NAMES]
# Generated or vendored code, and upstream submissions written in upstream's style.
SKIP = re.compile(r"(^|/)(pkg|cargokit|runner|Runner|l10n|flutter|Flutter|generated|vendor|node_modules|upstream)(/|$)"
                  r"|\.g\.dart$|\.freezed\.dart$|_pb2\.py$|\.pb\.")
GENERATED = re.compile(r"GENERATED CODE|DO NOT (EDIT|MODIFY)|Code generated by|This file (was|is) (auto-?)?generated"
                       r"|@generated|AUTO-?GENERATED", re.I)
# Comment-shaped lines that are not prose: headers, directives, markers.
NOT_PROSE = re.compile(r"SPDX-License-Identifier|Copyright|^\W*\(c\)|All rights reserved|Licensed under|Use of this source code"
                       r"|found in the LICENSE file|^#!|-\*-.*-\*-|#requires|^#\s*(escape|syntax|check)="
                       r"|shellcheck |hadolint |noqa|type:\s*ignore|pylint:|ruff:|fmt:|pragma|isort:|pyright:|mypy:"
                       r"|NOLINT|clang-format|ignore_for_file|//\s*ignore:|eslint|#region|#endregion"
                       r"|yaml-language-server|renovate:|^#\s*\[|^//\s*SAFETY:", re.I)
HEREDOC = re.compile(r"<<-?\s*['\"]?([A-Za-z_][A-Za-z0-9_]*)['\"]?")


def style(rel):
    base = os.path.basename(rel)
    ext = os.path.splitext(base)[1].lower()
    if ext in HASH or base.startswith(HASH_NAMES):
        return "#"
    if ext in SLASH:
        return "//"
    return None


def _prose(text):
    return bool(text.strip()) and not NOT_PROSE.search(text.strip())


def _heredoc_word(line):
    """The delimiter of a heredoc this shell line opens; `<<` inside quotes or a comment opens none."""
    quote, i = None, 0
    while i < len(line):
        c = line[i]
        if quote:
            if c == "\\" and quote == '"':
                i += 2
                continue
            if c == quote:
                quote = None
        elif c in ("'", '"'):
            quote = c
        elif c == "#" and (i == 0 or line[i - 1] in " \t"):
            return None
        elif line.startswith("<<", i) and not line.startswith("<<<", i):
            m = HEREDOC.match(line, i)
            if m:
                return m.group(1)
        i += 1
    return None


def _ps_quote_after(line, quote):
    """What is still open at the end of a PowerShell ``line``: None, "'", '"' or "<#" (a block comment)."""
    i = 0
    while i < len(line):
        c = line[i]
        if quote == "<#":
            if line.startswith("#>", i):
                quote = None
                i += 2
                continue
        elif quote == "'":
            if c == "'" and line[i + 1:i + 2] == "'":  # '' is an escaped quote
                i += 2
                continue
            quote = None if c == "'" else quote
        elif quote == '"':
            if c == "`":
                i += 2
                continue
            quote = None if c == '"' else quote
        elif line.startswith("<#", i):
            quote = "<#"
            i += 2
            continue
        elif c == "#":
            return None
        elif c in ("'", '"'):
            quote = c
        i += 1
    return quote


def _hash_flags(src, shell, powershell):
    flags, end, here, quote = [], None, False, None
    for line in src.split("\n"):
        s = line.strip()
        if end is not None:  # heredoc bodies are data
            flags.append(False)
            end = None if s == end else end
            continue
        if here:  # so are PowerShell here-strings
            flags.append(False)
            here = not s.startswith(('"@', "'@"))
            continue
        if quote:  # and multi-line PowerShell strings
            flags.append(False)
            quote = _ps_quote_after(line, quote)
            continue
        flags.append(s.startswith("#") and _prose(s))
        if shell and not s.startswith("#"):
            end = _heredoc_word(line)
        if powershell and not s.startswith("#"):
            if re.search(r"@[\"']\s*$", line):
                here = True
            else:
                quote = _ps_quote_after(line, None)
    return flags


def _python_flags(src):
    lines = src.split("\n")
    flags, code = [False] * len(lines), set()
    try:
        for tok in tokenize.generate_tokens(io.StringIO(src).readline):
            if tok.type == tokenize.COMMENT:
                row = tok.start[0] - 1
                flags[row] = lines[row].strip().startswith("#") and _prose(tok.string)
            elif tok.type not in (tokenize.NL, tokenize.NEWLINE, tokenize.INDENT, tokenize.DEDENT, tokenize.ENDMARKER):
                code.update(range(tok.start[0] - 1, tok.end[0]))
    except (tokenize.TokenError, IndentationError, SyntaxError):
        return _hash_flags(src, False, False)
    return [f and i not in code for i, f in enumerate(flags)]


def _slash_flags(src):
    flags, in_block, doc = [], False, False
    for line in src.split("\n"):
        s = line.strip()
        if in_block:
            body = s.strip("*/ ")
            flags.append(not doc and (not body or _prose(body)))
            in_block = "*/" not in s
            continue
        if s.startswith("/*"):
            doc = s.startswith(("/**", "/*!"))  # API docs
            in_block = "*/" not in s[2:]
            # `/*arg=*/ 3,` is code with an inline label, not a comment line.
            code_after = not in_block and s[s.index("*/", 2) + 2:].strip()
            flags.append(not doc and not code_after and _prose(s))
            continue
        flags.append(s.startswith("//") and not s.startswith(("///", "//!")) and _prose(s))
    return flags


def file_blocks(path, rel):
    """(start_line, length) of every comment block longer than LIMIT lines in one file."""
    k = style(rel)
    if not k or SKIP.search(rel):
        return []
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            src = fh.read().replace("\r\n", "\n")
    except OSError:
        return []
    if GENERATED.search(src[:1500]):
        return []
    ext = os.path.splitext(rel)[1].lower()
    if ext == ".py":
        flags = _python_flags(src)
    elif k == "#":
        flags = _hash_flags(src, ext in (".sh", ".bash") or src.startswith("#!"), ext in (".ps1", ".psm1", ".psd1"))
    else:
        flags = _slash_flags(src)
    out, n, start = [], 0, 0
    for i, f in enumerate(flags + [False], 1):
        if f:
            start = i if n == 0 else start
            n += 1
            continue
        if n > LIMIT:
            out.append((start, n))
        n = 0
    return out


def scan_paths(root, scan):
    rels = gate_scope.tracked(root, PATTERNS)
    if scan:
        rels = [r for r in rels if any(r == s or r.startswith(s.rstrip("/") + "/") for s in scan)]
    return sorted(rels)


def blocks(root, rels):
    return [(rel, start, n) for rel in rels for start, n in file_blocks(os.path.join(root, rel), rel)]


def main():
    ap = argparse.ArgumentParser(description="Fail on new comment blocks over the limit.")
    ap.add_argument("--root", default=None,
                    help="the tree to grade (default: this repo)")
    ap.add_argument("--allow", default=None,
                    help="the freeze file (default: comment-size.allow beside this "
                         "script for the hub, <root>/comment-size.allow otherwise)")
    ap.add_argument("--scan", action="append",
                    help="restrict to this top-level directory (repeatable)")
    args = ap.parse_args()
    try:
        # resolve_root, not abspath: a subdirectory root would silently shift every allowlist key.
        root = gate_scope.resolve_root(args.root, ROOT)
        found = blocks(root, scan_paths(root, args.scan))
    except gate_scope.ScopeError as exc:
        return gate_scope.die(exc)
    # A consumer's freeze lives in the consumer, where its own diff shows it.
    allow = args.allow or (ALLOW if root == os.path.abspath(ROOT)
                           else os.path.join(root, "comment-size.allow"))
    frozen = load_keys(allow)
    # Keyed on the block's first comment text, not its line number, so moves above it do not re-flag.
    keys = {}
    for rel, start, n in found:
        with open(os.path.join(root, rel), encoding="utf-8", errors="replace") as fh:
            # rstrip after truncating, or a trailing space would not survive the allowlist round-trip.
            first = fh.readlines()[start - 1].strip()[:60].rstrip()
        keys["{}\t{}".format(rel, first)] = (start, n)

    print("=== comment size gate (limit {} line{}) ===".format(LIMIT, "" if LIMIT == 1 else "s"))
    if root != os.path.abspath(ROOT):
        print("  root: {}".format(root))
        print("  allow: {}".format(allow))
    print("  {} block(s) over the limit; {} frozen".format(len(keys), len(frozen)))

    def _block(k):
        rel, _ = k.split("\t")
        start, n = keys[k]
        return "{}:{}  {} lines".format(rel, start, n)

    rc = check_keys(keys, frozen,
                    "NEW comment block(s) over the limit: one line, only the why (AGENTS.md § Comments):",
                    "STALE entr(ies) — that block is gone or now fits, delete the line:", _block)
    if rc == 0:
        print("OK: no new oversized comment blocks")
    return rc


if __name__ == "__main__":
    sys.exit(main())
