#!/usr/bin/env bash
set -euo pipefail

# Swaps the host GCC for the cross-built target-native one; env: TARGET_ARCH, GCC_VERSION, BUILD_MODE.

_swap_gcc_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
for _swap_mod_path in \
  "${_swap_gcc_script_dir}/../01-core/modules.sh" \
  "/opt/scripts/core/modules.sh"; do
  if [ -f "${_swap_mod_path}" ]; then
    # shellcheck disable=SC1090
    source "${_swap_mod_path}"
    break
  fi
done
source_module platform.sh

_assert_and_relocate_native_gcc() {
  local native_gcc="$1"
  if [ ! -d "${native_gcc}" ]; then
    echo "ERROR: expected target-native GCC at ${native_gcc} but not found" >&2
    echo "ERROR: Rebuild the toolchain image (build-cross-compiler.sh) to produce" >&2
    echo "ERROR: the Canadian cross GCC, then rebuild this android image." >&2
    exit 1
  fi

  assert_elf_arch "${native_gcc}/bin/gcc" "${TARGET_ARCH}"
  assert_elf_arch "${native_gcc}/bin/g++" "${TARGET_ARCH}"

  rm -rf "/opt/gcc-${GCC_VERSION}"
  cp -a "${native_gcc}" "/opt/gcc-${GCC_VERSION}"

  assert_elf_arch "/opt/gcc-${GCC_VERSION}/bin/gcc" "${TARGET_ARCH}"
  echo "Replaced host GCC with target-native ${TARGET_ARCH} GCC at /opt/gcc-${GCC_VERSION}"
}

# The relocated GCC's target lib/include dirs are empty; point them at the image's multiarch dirs.
_link_multiarch_dirs() {
  local triplet="$1"
  local gcc_target_lib="/opt/gcc-${GCC_VERSION}/${triplet}/lib"
  local sys_multiarch_lib="/usr/lib/${triplet}"
  if [ ! -d "${gcc_target_lib}" ] || [ -z "$(ls -A "${gcc_target_lib}" 2>/dev/null)" ]; then
    rm -rf "${gcc_target_lib}"
    mkdir -p "$(dirname "${gcc_target_lib}")"
    ln -sf "${sys_multiarch_lib}" "${gcc_target_lib}"
    echo "Linked GCC target lib ${gcc_target_lib} -> ${sys_multiarch_lib}"
  fi

  local gcc_target_include="/opt/gcc-${GCC_VERSION}/${triplet}/include"
  local sys_multiarch_include="/usr/include/${triplet}"
  if [ ! -e "${gcc_target_include}" ]; then
    mkdir -p "$(dirname "${gcc_target_include}")"
    ln -sf "${sys_multiarch_include}" "${gcc_target_include}"
    echo "Linked GCC target include ${gcc_target_include} -> ${sys_multiarch_include}"
  fi
}

# Inlined twin of common.sh's append_cross_idirafter (android stage lacks it). docs/cross-build-verification.md#swapping-the-native-gcc-in-the-shipped-image
_write_native_gcc_profile_d() {
  local triplet="$1"
  mkdir -p /etc/profile.d
  cat > /etc/profile.d/50-native-gcc-paths.sh <<EOF
_idaf="-idirafter /usr/include/${triplet} -idirafter /usr/include"
export CPATH="\${CPATH:+\${CPATH}:}/usr/include/${triplet}:/usr/include"
export CPPFLAGS="\${CPPFLAGS:+\${CPPFLAGS} }\${_idaf}"
export CFLAGS="\${CFLAGS:+\${CFLAGS} }\${_idaf}"
export CXXFLAGS="\${CXXFLAGS:+\${CXXFLAGS} }\${_idaf}"
export LIBRARY_PATH="\${LIBRARY_PATH:+\${LIBRARY_PATH}:}/usr/lib/${triplet}:/usr/lib"
EOF
  echo "Wrote /etc/profile.d/50-native-gcc-paths.sh (CPATH/*FLAGS/LIBRARY_PATH -> system dirs)"
}

# Wrappers, not a specs file. See docs/cross-build-verification.md#swapping-the-native-gcc-in-the-shipped-image
_wrap_native_gcc_drivers() {
  local triplet="$1"
  local gcc_bindir="/opt/gcc-${GCC_VERSION}/bin"
  local _wrapped=0 _tool _real
  for _tool in gcc g++ cpp cc c++ gfortran gccgo \
               "${triplet}-gcc" "${triplet}-g++" "${triplet}-cpp"; do
    _real="${gcc_bindir}/${_tool}"
    # Symlinks resolve to a wrapped target already; wrapping them would double-add -idirafter.
    [ -e "${_real}" ] || continue
    [ -L "${_real}" ] && continue
    [ -e "${_real}.real" ] && continue
    mv "${_real}" "${_real}.real"
    cat > "${_real}" <<EOF
#!/bin/sh
# Auto-generated by swap-native-gcc.sh: point the relocated Canadian-cross native
# compiler at the runtime image's system headers via -idirafter (its baked
# --native-system-header-dir is a build-time-only path). Command-line injection,
# NOT an installed specs file, so C++ exception link specs (-lgcc_s /
# --eh-frame-hdr) stay intact. Honour -nostdinc/-nostdinc++ (true cross use).
for a in "\$@"; do
  case "\$a" in -nostdinc|-nostdinc++) exec "${_real}.real" "\$@";; esac
done
exec "${_real}.real" -idirafter /usr/include/${triplet} -idirafter /usr/include "\$@"
EOF
    chmod +x "${_real}"
    _wrapped=$((_wrapped + 1))
  done
  echo "Wrapped ${_wrapped} native-GCC driver(s) with -idirafter system-header injection"

  # A stale specs file would re-break exceptions even with the wrappers in place.
  local gcclib="/opt/gcc-${GCC_VERSION}/lib/gcc/${triplet}/${GCC_VERSION}"
  rm -f "${gcclib}/specs"
}

# Trivial compile smoke, with riscv64 ISA-spec-skew classification.
_smoke_native_gcc() {
  echo "int main(){}" > /tmp/gcc_smoke.c
  if /opt/gcc-${GCC_VERSION}/bin/gcc /tmp/gcc_smoke.c -o /tmp/gcc_smoke 2>/tmp/gcc_smoke.err; then
    file /tmp/gcc_smoke
    echo "GCC compile smoke test PASSED"
  else
    # A riscv64 -march its bundled `as` rejects is a known, non-fatal ISA-spec skew; log a NOTE, not the raw error.
    if grep -q 'invalid -march=' /tmp/gcc_smoke.err 2>/dev/null; then
      echo "NOTE: native ${TARGET_ARCH} GCC default -march uses ISA-spec profile extension names its bundled assembler does not accept (known GCC/binutils ISA-spec skew; non-fatal for cross builds -- affects only on-device compilation). Tracked as build-arg RISCV_GCC_ISA_SPEC in the toolchain build."
    else
      echo "WARNING: native GCC cannot compile trivial program (cross-build host limitation)"
      sed 's/^/    /' /tmp/gcc_smoke.err 2>/dev/null || true
    fi
  fi
  rm -f /tmp/gcc_smoke.c /tmp/gcc_smoke /tmp/gcc_smoke.err
}

# hwasan only where GCC's configure.tgt builds it. docs/cross-build-verification.md#the-native-gcc-ships-libsanitizer
_assert_native_gcc_sanitizers() {
  local prefix="$1" arch="$2" lib hit missing=""
  local -a libs=(asan ubsan lsan tsan)
  case "${arch}" in amd64|arm64) libs+=(hwasan) ;; esac
  compgen -G "${prefix}/lib/gcc/*/${GCC_VERSION}/include/sanitizer/common_interface_defs.h" >/dev/null \
    || missing+=" sanitizer/common_interface_defs.h"
  for lib in "${libs[@]}"; do
    hit="$(compgen -G "${prefix}/lib64/lib${lib}.so.*.*" || compgen -G "${prefix}/lib/lib${lib}.so.*.*" || true)"
    if [ -z "${hit}" ]; then missing+=" lib${lib}.so"; else assert_elf_arch "${hit%%$'\n'*}" "${arch}"; fi
  done
  [ -z "${missing}" ] || { echo "ERROR: ${prefix} lacks the sanitizer runtime:${missing} (rebuild the toolchain image)" >&2; exit 1; }
  echo "Sanitizer runtime present in ${prefix}: ${libs[*]}"
}

# CMake reads CMAKE_LIBRARY_ARCHITECTURE from the multiarch; checked only where the target runs. docs/cross-build-verification.md#the-native-gcc-has-multiarch
_assert_native_gcc_multiarch() {
  local gcc="$1" triplet="$2" got
  if ! "${gcc}" -dumpversion >/dev/null 2>&1; then
    echo "NOTE: ${gcc} does not run on this build host; its multiarch is not checked here"
    return 0
  fi
  got="$("${gcc}" -print-multiarch 2>/dev/null || true)"
  [ "${got}" = "${triplet}" ] || { echo "ERROR: ${gcc} -print-multiarch prints '${got}', not '${triplet}' (rebuild the toolchain image)" >&2; exit 1; }
  echo "Native GCC multiarch: ${got}"
}

main() {
  : "${TARGET_ARCH:?TARGET_ARCH is required}"
  : "${GCC_VERSION:?GCC_VERSION is required}"

  # Decide by build host like gcc.sh: it builds no native prefix for the host's own arch.
  local build_arch
  build_arch="$(build_arch_oci)"
  if [ "${TARGET_ARCH}" = "${build_arch}" ]; then
    assert_elf_arch "/opt/gcc-${GCC_VERSION}/bin/gcc" "${TARGET_ARCH}"
    _assert_native_gcc_sanitizers "/opt/gcc-${GCC_VERSION}" "${TARGET_ARCH}"
    echo "Using host-native ${TARGET_ARCH} GCC at /opt/gcc-${GCC_VERSION}"
    return 0
  fi
  # Non-amd64 but not a cross build: keep whatever GCC is already in place.
  if [ "${BUILD_MODE:-}" != "cross" ]; then
    return 0
  fi

  local native_gcc="/opt/gcc-${GCC_VERSION}-native-${TARGET_ARCH}"
  _assert_and_relocate_native_gcc "${native_gcc}"

  local triplet
  triplet="$(arch_deb_multiarch_triplet_for "${TARGET_ARCH}")"
  if [ -n "${triplet}" ]; then
    _link_multiarch_dirs "${triplet}"
    _write_native_gcc_profile_d "${triplet}"
    _wrap_native_gcc_drivers "${triplet}"
    _assert_native_gcc_multiarch "/opt/gcc-${GCC_VERSION}/bin/gcc" "${triplet}"
  fi
  _assert_native_gcc_sanitizers "/opt/gcc-${GCC_VERSION}" "${TARGET_ARCH}"

  _smoke_native_gcc
}

main "$@"